HRMSWebpage/Controllers/HRController.cs
using HRMSWebpage.Entity.Models;
using HRMSWebpage.Service.Repository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HRMSWebpage.Controllers
{
    public class HRController : Controller
    {
        private readonly IHRMSRepository _repository;

        public HRController(IHRMSRepository repository)
        {
            _repository = repository;
        }

        // Leave

        [HttpGet]
        public JsonResult ListLeavesDataTable()
        {
            var leaveDetails = _repository.GetEmployeeLeaveView();
            return Json(new { data = leaveDetails });
        }

        public IActionResult LeaveRequestApprover()
        {
            return View();
        }

        public IActionResult ApproveLeaveAppById(int id)
        {
            var leaveapp = _repository.LeaveDetailsById(id);
            leaveapp.Status = "Approved";
            _repository.ApproveLeaveAppById(leaveapp);
            return RedirectToAction("LeaveRequestApprover");
        }

        public IActionResult RejectLeaveAppById(int id)
        {
            var leaveapp = _repository.LeaveDetailsById(id);
            leaveapp.Status = "Rejected";
            _repository.ApproveLeaveAppById(leaveapp);
            return RedirectToAction("LeaveRequestApprover");
        }


        // Training


        /// <summary>
        [HttpGet]
        public JsonResult ListTrainingDataTable()
        {
            var TrainingDetails = _repository.GetTrainingView();
            return Json(new { data = TrainingDetails });
        }
        /// </summary>


        public IActionResult TrainingRequestApprover()
        {
            return View();
        }
        public IActionResult ApproveTrainingAppById(int id)
        {
            var trainingapp = _repository.GetTrainingFullDetailsById(id);
            trainingapp.Status = "Approved";
            _repository.ApproveTrainingAppById(trainingapp);
            return RedirectToAction("TrainingRequestApprover");
        }

        public IActionResult RejectTrainingAppById(int id)
        {
            var trainingapp = _repository.GetTrainingFullDetailsById(id);
            trainingapp.Status = "Rejected";
            _repository.ApproveTrainingAppById(trainingapp);
            return RedirectToAction("TrainingRequestApprover");
        }
        public IActionResult DoneTrainingAppById(int id)
        {
            var trainingapp = _repository.GetTrainingFullDetailsById(id);
            trainingapp.Status = "Done";
            _repository.ApproveTrainingAppById(trainingapp);
            return RedirectToAction("TrainingRequestApprover");
        }
        public IActionResult RemoveTrainingAppById(int id)
        {
            var trainingapp = _repository.GetTrainingFullDetailsById(id);
            trainingapp.Status = "Removed";
            _repository.ApproveTrainingAppById(trainingapp);
            return RedirectToAction("TrainingRequestApprover");
        }

        // Projects
        public IActionResult ProjectRequestApprover()
        {
            var result = _repository.GetAllEmployees();
            ViewBag.Employee = new SelectList(result, "EmpId", "FirstName");
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> ListProjectDataTable()
        {
            var ProjectDetails = await _repository.GetAllProjects();
            return Json(new { data = ProjectDetails });
        }

        public JsonResult AddProjectApp(int prjtId, string empId, string startDate, string endDate)
        {
            ProjectApplication projApp = new ProjectApplication()
            {
                EmpId = empId,
                PrjtId = prjtId,
                ProjectStatus = "Ongoing",
                StartTime = DateTime.Parse(startDate),
                EndTime= DateTime.Parse(endDate)
            };
            _repository.AddProjectApp(projApp);
            return Json(true);
        }
        public JsonResult EditProjectApp(string empId, int prjtId)
        {
            var projectapp = _repository.GetProjectFullDetailsByIds(empId, prjtId);
            projectapp.ProjectStatus = "Relieved";
            _repository.UpdateProjectApp(projectapp);
            return Json(true);
        }
    }
}

HRMSWebpage/Views/HR/LeaveRequestApprover.cshtml
@model LeaveViewModel

@{
    Layout = "_HRMSLayout";
}


<div class="container">
    <div class="card-header d-flex justify-content-between">
        Leave Requests
        @*<div>
            <a href="#" class="fa fa-add btn btn-primary" id="addBtn"></a>
        </div>*@
    </div>
    <div class="card-body">
        <table class="table table-bordered" id="MyTable">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(data => data.FirstName)</th>
                    <th>@Html.DisplayNameFor(data => data.LeaveName)</th>
                    <th>@Html.DisplayNameFor(data => data.StartDate)</th>
                    <th>@Html.DisplayNameFor(data => data.EndDate)</th>
                    <th>@Html.DisplayNameFor(data => data.Days)</th>
                    <th>@Html.DisplayNameFor(data => data.Description)</th>
                    <th>@Html.DisplayNameFor(data => data.Status)</th>
                    <th>Actions</th>

                </tr>

            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div class="card-footer"></div>
</div>


@section scripts{
    <script>
        $(document).ready(function () {

            $('#MyTable').DataTable({
                "processing": false,
                "serverSide": false,
                "filter": true,
                "searching": false,
                "ajax": {
                    "url": "@Url.Action("ListLeavesDataTable","HR")",
                    "type": "GET",
                    "datatype": "json"
                },

                "columns": [
                    { "data": "firstName", "name": "FirstName", "autoWidth": true },
                    { "data": "leaveName", "name": "LeaveName", "autoWidth": true },
                    {
                        "data": "startDate", "name": "StartDate", "autoWidth": true, render: function (data, type, row) {
                            return moment(data).format("DD-MM-YYYY");
                        }
                    },
                    {
                        "data": "endDate", "name": "EndDate", "autoWidth": true, render: function (data, type, row) {
                            return moment(data).format("DD-MM-YYYY");
                        }
                    },
                    { "data": "days", "name": "Days", "autoWidth": true },
                    { "data": "description", "name": "Description", "autoWidth": true },
                    { "data": "status", "name": "Status", "autoWidth": true },

                    {
                        "render": function (data, type, full, meta) {
                            if(full.status == "Pending"){
                                return '<a href="ApproveLeaveAppById/' + full.leaveAppId + '" class="btn btn-primary approveBtn" >Approve</a> <a href="RejectLeaveAppById/' + full.leaveAppId + '" class="btn btn-danger rejectBtn" >Reject</a>';
                            }
                            else{
                                return '<a class="btn btn-secondary approveBtn" ><i class="fas fa-fw fa-thumbs-up"></i></a>';
                            }
                        }
                    }
                ]
            });
        });
    </script>
}



HRMSWebpage/Views/HR/ProjectRequestApprover.cshtml
@model ProjectViewModel

@{
    Layout = "_HRMSLayout";
}


<div class="container">
    <div class="card-header d-flex justify-content-between">
        Project Allocation
        @*<div>
        <a href="#" class="fa fa-add btn btn-primary" id="addBtn"></a>
        </div>*@
    </div>
    <div class="card-body">
        <table class="table table-bordered" id="MyTable">
            <thead>
                <tr>
                    <th>@Html.DisplayNameFor(data => data.PrjtId)</th>
                    <th>@Html.DisplayNameFor(data => data.PrjtName)</th>
                    <th>@Html.DisplayNameFor(data => data.PrjtDescription)</th>
                    <th>Actions</th>

                </tr>

            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div class="card-footer"></div>
</div>


@*Assign Project*@
<div class="modal fade" id="modalForm" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content shadow">
            <div class="modal-header">
                <h5 class="modal-title">Project Assigning</h5>
                <button type="button" id="close" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body bg-image" style="background-image: url()">
                <div class="form-group mx-2 mb-3">

                    <select asp-for="EmpId" asp-items="ViewBag.Employee" id="ViewBagProject" style="width:100%">
                        <option value="-1">-Select Employee-</option>

                    </select>

                    <label for="Project Name">Project Start Date</label>
                    <input type="datetime-local" class="form-control" id="prjtstart" placeholder="" required="">
                    <label for="Project Name">Project End Date</label>
                    <input type="datetime-local" class="form-control" id="prjtend" placeholder="" required="">
                </div>
            </div>
            <div class="modal-footer justify text-14">
                <button id="assignSubmit" type="submit" class="btn btn-primary" data-bs-dismiss="modal">Save Changes</button>
            </div>
        </div>
    </div>
</div>

@*Remove Assigned*@
<div class="modal fade" id="modalFormRemove" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content shadow">
            <div class="modal-header">
                <h5 class="modal-title">Relieve From Project</h5>
                <button type="button" id="close" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body bg-image" style="background-image: url()">
                <div class="form-group mx-2 mb-3">

                    <select asp-for="EmpId" asp-items="ViewBag.Employee" id="ViewBagProjectR" style="width:100%">
                        <option value="-1">-Select Employee-</option>

                    </select>

                </div>
            </div>
            <div class="modal-footer justify text-14">
                <button id="removeSubmit" type="submit" class="btn btn-danger" data-bs-dismiss="modal">Remove</button>
            </div>
        </div>
    </div>
</div>



@section scripts{
    <script>
        $(document).ready(function () {
            $('#ViewBagProject').select2({
                theme: "bootstrap4",
                placeholder: "Project Name",
                allowClear: true
            });

            $('#ViewBagProjectR').select2({
                theme: "bootstrap4",
                placeholder: "Project Name",
                allowClear: true
            });

            $('#MyTable').DataTable({
                "processing": false,
                "serverSide": false,
                "filter": true,
                "searching": false,
                "ajax": {
                    "url": "@Url.Action("ListProjectDataTable","HR")",
                    "type": "GET",
                    "datatype": "json"
                },

                "columns": [

                    { "data": "prjtId", "name": "PrjtId", "autoWidth": true },
                    { "data": "prjtName", "name": "PrjtName", "autoWidth": true },
                    { "data": "prjtDescription", "name": "PrjtDescription", "autoWidth": true },

                    {
                        "render": function (data, type, full, meta) {
                            return '<a onclick=LoadModal("' + full.prjtId + '"); class="btn btn-primary edit"  ><i class="fa fa-pencil-square"></i></a>  <a onclick=RemoveModal("' + full.prjtId + '"); class="btn btn-danger delete"  ><i class="fa fa-trash"></i></a> ';
                        }
                    }
                ]
            });


        });

        function LoadModal(prjtId) {
            $('#modalForm').modal('show');
            $('#assignSubmit').click(function () {
                var startDay = new Date($('#prjtstart').val());
                var dateS = startDay.getDate();
                var monthS = startDay.getMonth() + 1;
                var yearS = startDay.getFullYear();
                var startDate = dateS + "-" + monthS + "-" + yearS;

                var endDay = new Date($('#prjtend').val());
                var dateE = startDay.getDate();
                var monthE = startDay.getMonth() + 1;
                var yearE = startDay.getFullYear();
                var endDate = dateE + "-" + monthE + "-" + yearE;

                var empId = $('#ViewBagProject').val();

                $.ajax({
                    "type": "GET",
                    "url": "@Url.Action("AddProjectApp")",
                    "dataType": "json",
                    "data": { "prjtId": prjtId, "empId": empId, "startDate": startDate, "endDate": endDate },
                    "success": function (data) {
                        window.location.href = '@Url.Action("ProjectRequestApprover","HR")'
                        setinterval('location.reload()', 1000);
                    },
                    "error": function () {
                        alert("Error Occured");
                    }
                });
                
            });
        }

        function RemoveModal(prjtId) {
            $('#modalFormRemove').modal('show');
            $('#removeSubmit').click(function () {

                var empId = $('#ViewBagProjectR').val();

                $.ajax({
                    "type": "GET",
                    "url": "@Url.Action("EditProjectApp")",
                    "dataType": "json",
                    "data": { "prjtId": prjtId, "empId": empId },
                    "success": function (data) {
                        window.location.href = '@Url.Action("ProjectRequestApprover","HR")'
                        setinterval('location.reload()', 1000);
                    },
                    "error": function () {
                        alert("Error Occured");
                    }
                });
                
            });
        }

    </script>
}

HRMSWebpage/Views/HR/TrainingRequestApprover.cshtml
@model TrainingViewModel

@{
    Layout = "_HRMSLayout";
}


<div class="container">
    <div class="card-header d-flex justify-content-between">
        Training Requests
    </div>
    <div class="card-body">
        <table class="table table-bordered" id="MyTable">
            <thead>
                <tr>
                    @*<th>@Html.DisplayNameFor(data => data.FirstName)</th>
                    <th>@Html.DisplayNameFor(data => data.TrainingName)</th>
                    <th>@Html.DisplayNameFor(data => data.StartDate)</th>
                    <th>@Html.DisplayNameFor(data => data.EndDate)</th>
                    <th>@Html.DisplayNameFor(data => data.TrainingDetails)</th>
                    <th>@Html.DisplayNameFor(data => data.Status)</th>*@
                    <th>Name</th>
                    <th>Training Name</th>
                    <th>Start Date</th>
                    <th>End Date</th>
                    <th>Training Details</th>
                    <th>Status</th>
                    <th>Actions</th>

                </tr>

            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div class="card-footer"></div>
</div>


@section scripts{
    <script>
        $(document).ready(function () {

            $('#MyTable').DataTable({
                "processing": false,
                "serverSide": false,
                "filter": true,
                "searching": false,
                "ajax": {
                    "url": "@Url.Action("ListTrainingDataTable","HR")",
                    "type": "GET",
                    "datatype": "json"
                },

                "columns": [
                    { "data": "firstName", "name": "FirstName", "autoWidth": true },
                    { "data": "trainingName", "name": "TrainingName", "autoWidth": true },
                    {
                        "data": "startDate", "name": "StartDate", "autoWidth": true, render: function (data, type, row) {
                            return moment(data).format("DD-MM-YYYY");
                        }
                    },
                    {
                        "data": "endDate", "name": "EndDate", "autoWidth": true, render: function (data, type, row) {
                            return moment(data).format("DD-MM-YYYY");
                        }
                    },
                    { "data": "trainingDetails", "name": "TrainingDetails", "autoWidth": true },
                    { "data": "status", "name": "Status", "autoWidth": true },

                    {
                        "render": function (data, type, full, meta) {
                            if (full.status == "Pending") {
                                return '<a href="ApproveTrainingAppById/' + full.trainingAppId + '" class="btn btn-primary approveBtn" ><i class="fas fa-fw fa-check"></i></a> <a href="RejectTrainingAppById/' + full.trainingAppId + '" class="btn btn-danger rejectBtn" ><i class="fas fa-fw fa-xmark"></i></a>';
                            }
                            else if ((full.status == "Approved") || (full.status == "Rejected")){
                                return '<a href="DoneTrainingAppById/' + full.trainingAppId + '" class="btn btn-primary approveBtn" ><i class="fas fa-fw fa-square-check"></i></a> <a href="RemoveTrainingAppById/' + full.trainingAppId + '" class="btn btn-danger rejectBtn" ><i class="fas fa-fw fa-trash"></i></a>';
                                
                            }
                            else {
                                return '<a class="btn btn-primary" ><i class="fas fa-fw fa-thumbs-up"></i></a>';
                            }
                        }
                    }
                ]
            });
        });
    </script>
}