HRMSWebpage/Controllers/HRMSController.cs
using HRMSWebpage.Entity.Models;
using HRMSWebpage.Service.Repository;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace HRMSWebpage.Controllers
{
    public class HRMSController : Controller
    {
        private readonly IHRMSRepository _repository;
        private readonly UserManager<IdentityUser> _userManager;

        public HRMSController(IHRMSRepository repository, UserManager<IdentityUser> userManager)
        {
            _repository = repository;
            _userManager = userManager;
        }
        public IActionResult LandingPage()
        {
            var UserEmail = User.Identity.Name;
            var user = _repository.GetFullDetailsOfEmployeeByEmail(UserEmail);
            var actualLeaveDaysA = _repository.GetLeavesById(1);
            var alreadyAllottedLeavesA = _repository.GetLeavesAllotted(user.EmpId, 1);
            var AnnualLeaves = actualLeaveDaysA - alreadyAllottedLeavesA;

            var actualLeaveDaysC = _repository.GetLeavesById(3);
            var alreadyAllottedLeavesC = _repository.GetLeavesAllotted(user.EmpId, 3);
            var CasualLeaves = actualLeaveDaysC - alreadyAllottedLeavesC;

            var actualLeaveDaysS = _repository.GetLeavesById(4);
            var alreadyAllottedLeavesS = _repository.GetLeavesAllotted(user.EmpId, 4);
            var SickLeaves = actualLeaveDaysS - alreadyAllottedLeavesS;

            var actualLeaveDaysU = _repository.GetLeavesById(5);
            var alreadyAllottedLeavesU = _repository.GetLeavesAllotted(user.EmpId, 5);
            var UnpaidLeaves = actualLeaveDaysU - alreadyAllottedLeavesU;

            ViewBag.CasualLeave = CasualLeaves;
            ViewBag.AnnualLeave = AnnualLeaves;
            ViewBag.SickLeave = SickLeaves;
            ViewBag.UnpaidLeave = UnpaidLeaves;

            return View();
        }

        // Employee
        [AllowAnonymous]
        public IActionResult SearchEmployee(string EmpName)
        {
            var query = _repository.SearchEmployee().AsQueryable();
            if (!string.IsNullOrWhiteSpace(EmpName))
            {
                query = query.Where(emp => emp.FirstName.Contains(EmpName,StringComparison.CurrentCultureIgnoreCase));
            }
            return View(query.ToList());
        }


        // Leaves

        [HttpGet]
        public IActionResult LeaveTracker()
        {
            var leaves = _repository.GetAllLeavesName();
            ViewBag.Leaves = new SelectList(leaves, "LeaveId", "LeaveName");
            return View();
        }

        [HttpGet]
        public JsonResult ListLeavesDataTable()
        {
            var UserEmail = User.Identity.Name;
            var leaveDetails = _repository.GetEmployeeLeaveView(UserEmail);
            return Json(new { data = leaveDetails });
        }

        [HttpPost]
        public JsonResult LeaveTracker(string startDate, string endDate, int days, string description, int leaveId)
        {
            var UserEmail = User.Identity.Name;
            var result = _repository.GetFullDetailsOfEmployeeByEmail(UserEmail);
            LeaveApplication model = new LeaveApplication()
            {
                Days = days,
                Description = description,
                EmpId = result.EmpId,
                EndDate = DateTime.Parse(endDate),
                StartDate = DateTime.Parse(startDate),
                LeaveId = leaveId,
                Status = "Pending"
            };
            _repository.AddLeaveApplicationDetails(model);
            return Json(true);
        }

        public JsonResult LeavesRemaining(int leaveId, int requestedDays)
        {
            var UserEmail = User.Identity.Name;
            var user = _repository.GetFullDetailsOfEmployeeByEmail(UserEmail);
            var actualLeaveDays = _repository.GetLeavesById(leaveId);
            var alreadyAllottedLeaves = _repository.GetLeavesAllotted(user.EmpId, leaveId);
            var remaining = actualLeaveDays - alreadyAllottedLeaves;
            
            if (remaining >= requestedDays)
            {
                return Json(true);
            }
            else
            {
                return Json(false);
            }
        }

        public JsonResult DltLeaveAppById(int Id)
        {
            _repository.DeleteLeaveAppById(Id);
            return Json(true);
        }

        // Training
        [HttpGet]
        public IActionResult TrainingTracker()
        {
            var training = _repository.GetAllTrainingName();
            ViewBag.Trainings = new SelectList(training, "TrainingId", "TrainingName");
            return View();
        }

        [HttpGet]
        public JsonResult ListTrainingDataTable()
        {
            var UserEmail = User.Identity.Name;
            var TrainingDetails = _repository.GetTrainingView(UserEmail);
            return Json(new { data = TrainingDetails });
        }

        [HttpPost]
        public JsonResult TrainingTracker(string startDate, string endDate, string details, int trainingId)
        {
            var UserEmail = User.Identity.Name;
            var result = _repository.GetFullDetailsOfEmployeeByEmail(UserEmail);
            TrainingApplication model = new TrainingApplication()
            {
                EmpId = result.EmpId,
                EndDate = DateTime.Parse(endDate),
                StartDate = DateTime.Parse(startDate),
                Status = "Pending",
                TrainingId= trainingId,
                Description= details,                
            };
            _repository.AddTrainingApplicationDetails(model);
            return Json(true);
        }

        public JsonResult GetTrainingDetailsById(int Id)
        {
            var details = _repository.GetTrainingDetailsById(Id);
            return Json(details);
        }

        // Projects
        public IActionResult ProjectTracker()
        {
            var UserEmail = User.Identity.Name;
            var result = _repository.GetFullDetailsOfEmployeeByEmail(UserEmail);
            var model = _repository.ProjectAssignedToUser(result.EmpId);
            return View(model);
        }
    }
}

HRMSWebpage/Views/HRMS/LandingPage.cshtml
@{
    Layout = "_HRMSLayout";
}

<link href="~/css/style.css" rel="stylesheet" />

<div class="container">
    <div class="d-flex justify-content-between mr-3">
        Dashboard
        <input type="button" id="timer" class="btn btn-success" value="Log In" />
    </div>
</div>

<div class="container mt-4">
    <div class="row">

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow  py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Annual Leave
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">@ViewBag.AnnualLeave
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow  py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Casual Leave
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                @ViewBag.CasualLeave
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow  py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Sick Leave
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                @ViewBag.SickLeave
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <!-- Earnings (Monthly) Card Example -->
        <div class="col-xl-3 col-md-6 mb-4">
            <div class="card border-left-primary shadow  py-2">
                <div class="card-body">
                    <div class="row no-gutters align-items-center">
                        <div class="col mr-2">
                            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                                Unpaid Leave
                            </div>
                            <div class="h5 mb-0 font-weight-bold text-gray-800">
                                @ViewBag.UnpaidLeave
                            </div>
                        </div>
                        <div class="col-auto">
                            <i class="fas fa-calendar fa-2x text-gray-300"></i>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container mt-4">
    <div class="row">

        <div class="col-lg-4">

            <div class="card shadow mb-4 h-100">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Birthday</h6>
                </div>
                <div class="card-body">
                    No Birthday Today..
                </div>
            </div>
        </div>

        <div class="col-lg-4">

            <div class="card shadow mb-4 h-100">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">New Hires</h6>
                </div>
                <div class="card-body">
                    @*<i class="fa fa-cake-candles"></i>*@
                    No New Hires..!!!
                </div>
            </div>
        </div>

        <div class="col-lg-4">
            <div class="card shadow mb-4 h-100">
                <div class="card-header py-3">
                    <h6 class="m-0 font-weight-bold text-primary">Favorites</h6>
                </div>
                <div class="card-body">
                    No Favorites Found..!!
                </div>
            </div>

        </div>

    </div>
</div>


@section scripts
    {
    <script>
        $(document).ready(function () {
            var loggedInTime;
            var loggedOutTime;
            $('#timer').click(function () {
                loggedInTime = new Date().getTime();
                var currentTime = new Date();
                var countDownTime = currentTime.setHours(currentTime.getHours() + 10);

                var x = setInterval(function () {
                    var now = new Date().getTime();

                    var distance = countDownTime - now;

                    var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
                    var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
                    var seconds = Math.floor((distance % (1000 * 60)) / 1000);


                    $('#timer').val(hours + "h :"
                        + minutes + "m :" + seconds + "s ");

                    $('#timer').click(function () {
                        loggedOutTime = new Date().getTime();
                        console.log(loggedInTime);
                        console.log(loggedOutTime);
                        $('#timer').val("Logged Out");
                        window.location.href = '@Url.Action("LandingPage","HRMS")'
                    });

                    //if (distance < 0) {
                    //    clearInterval(x);
                    //    $('#timer').val("Thank you");
                    //}
                }, 1000);

                //$(this).setAttribute('disabled') = 'disabled';
            });

            $('#sickLeaves').val(12);

        });
    </script>
}


HRMSWebpage/Views/HRMS/LeaveTracker.cshtml
@model LeaveViewModel

@{
    Layout = "_HRMSLayout";
}


<div class="container">
    <div class="card-header d-flex justify-content-between">
        Leave Details
        <div>
            <a href="#" class="fa fa-add btn btn-primary" id="addBtn"></a>
        </div>
    </div>
    <div class="card-body">
        <table class="table table-bordered" id="MyTable">
            <thead>
            <tr>
                <th>@Html.DisplayNameFor(data => data.LeaveName)</th>
               <th>@Html.DisplayNameFor(data => data.StartDate)</th>
                <th>@Html.DisplayNameFor(data => data.EndDate)</th>
                <th>@Html.DisplayNameFor(data => data.Status)</th>
                <th>Actions</th>

            </tr>
           
            </thead>
            <tbody>
            </tbody>
        </table>
    </div>
    <div class="card-footer"></div>
</div>


@*Modal for Cancelling*@
<div id="myModal" class="modal fade">
    <div class="modal-dialog modal-confirm">
        <div class="modal-content">
            <div class="modal-header flex-column">
                <div class="icon-box">
                    <i class="fa fa-trash-can"></i>
                </div>
                <h4 class="modal-title w-100">Are you sure?</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <p>Do you really want to delete this records? This process cannot be undone.</p>
            </div>
            <div class="modal-footer justify-content-center">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="button" class="btn btn-danger" id="modalBtnDlt">Delete</button>
            </div>
        </div>
    </div>
</div>


@*Modal for Create Item*@
<div class="modal fade" id="modalFormAdd" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content shadow">
            <div class="modal-header">
                <h5 class="modal-title">Leave Application</h5>
                <button type="button" id="close" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body bg-image" style="background-image: url()">
                <div class="form-group mx-2 mb-3">
                    <label for="Leave Name">Leave Name</label>
                    @*<input type="text" class="form-control" id="leavename" placeholder="Enter the Leave Name" required="">*@
                  

                    <select asp-for="LeaveId" asp-items="ViewBag.Leaves" id="ViewBagLeave" style="width:100%">
                        <option value="-1">-Select Leave-</option>                        

                    </select>
                    <label for="StartDate">Start Date</label>
                    <input type="datetime-local" class="form-control" id="startDate" placeholder="Enter the Start Date" required="">
                    <label for="EndDate">End Date</label>
                    <input type="datetime-local" class="form-control" id="endDate" placeholder="Enter the End Date" required="">
                    <label for="Project Name">Days</label>
                    <input type="text" class="form-control" id="days" placeholder="Enter the Number of Days" required="" disabled>
                    <label for="Project Name">Description</label>
                    <input type="text" class="form-control" id="description" placeholder="Description" required="">

                </div>
            </div>
            <div class="modal-footer justify text-14">
                <button id="addSubmit" type="submit" class="btn btn-primary" data-bs-dismiss="modal">Add</button>
            </div>
        </div>
    </div>
</div>


@section scripts
    {
    <script>
        function CancelModal(id) {
            console.log(id);
            $('#myModal').modal('show');
            $('#modalBtnDlt').click(function () {
                $.ajax({
                    "type": "GET",
                    "url": "@Url.Action("DltLeaveAppById")",
                    "dataType": 'json',
                    "data": { "Id": id },
                    "success": function (data) {
                        //alert("success");
                        window.location.href = '@Url.Action("LeaveTracker","HRMS")'
                        setInterval('location.reload()', 1000);
                    },
                    "error": function (data) {
                        alert("failed");
                    }
                });
                
            });
        };

        $(document).ready(function () {

            $('#MyTable').DataTable({
                "processing": false,
                "serverSide": false,
                "filter": true, 
                "searching": false,
                "ajax": {
                    "url": "@Url.Action("ListLeavesDataTable","HRMS")",
                    "type": "GET",
                    "datatype": "json"
                },
                
                "columns": [

                    { "data": "leaveName", "name": "LeaveName", "autoWidth": true },
                    { "data": "startDate", "name": "StartDate", "autoWidth": true, render: function (data, type, row) {
                            return moment(data).format("DD-MM-YYYY");
                        } },
                    { "data": "endDate", "name": "EndDate", "autoWidth": true, render: function (data, type, row) {
                            return moment(data).format("DD-MM-YYYY");
                        } },
                    { "data": "status", "name": "Status", "autoWidth": true },

                    {
                        
                        "render": function (data, type, full, meta) {
                            if(full.status == "Pending"){
                            return '<a onclick=CancelModal("' + full.id + '"); class="btn btn-outline-primary cancelBtn" >Cancel</a>';
                            }
                            else if (full.status == "Approved") {
                                return '<a class="btn btn-success" >Approved</a>';
                            }
                            else{
                                return '<a class="btn btn-danger" >Rejected</a>';
                            }
                        }
                        
                        
                    }
                ]
            });

            $('#ViewBagLeave').select2({
                theme: "bootstrap4",
                placeholder: "Leave Name",
                allowClear: true
            });

            

            $('#endDate').blur(function () {
                var startDay = new Date($('#startDate').val());
                var endDay = new Date($('#endDate').val());

                if(startDay <= endDay){

                var millisBetween = startDay.getTime() - endDay.getTime();
                    var days = Math.round(Math.abs(millisBetween / (1000 * 3600 * 24)));

                    var leaveId = $('#ViewBagLeave').find(":selected").val();
                    console.log(leaveId);
                    $.ajax({
                        "type": "POST",
                        "url": "@Url.Action("LeavesRemaining")",
                        "datatype": 'json',
                        "data": { "leaveId": leaveId, "requestedDays": days },
                        "success": function (data) {
                            if(data == true){
                            $('#days').val(Math.round(Math.abs(days)));
                            }
                            else{
                                alert("Request Number of leaves not available");
                            }
                        },
                        "error": function (data) {
                            alert("Error");
                        }
                    });
                
                }
                else{
                    alert("End Date is Invalid");
                }

            });

            $('#addBtn').click(function () {
                $('#modalFormAdd').modal('show');
                $("#addSubmit").click(function () {
                    var startDay = new Date($('#startDate').val());
                    var dateS = startDay.getDate();
                    var monthS = startDay.getMonth() + 1;
                    var yearS = startDay.getFullYear();
                    var startDate = dateS + "-" + monthS + "-" + yearS;

                    var endDay = new Date($('#endDate').val());
                    var dateE = startDay.getDate();
                    var monthE = startDay.getMonth() + 1;
                    var yearE = startDay.getFullYear();
                    var endDate = dateE + "-" + monthE + "-" + yearE;

                    var description = $('#description').val();
                    var leaveId = $('#ViewBagLeave').val();
                    var millisBetween = startDay.getTime() - endDay.getTime();
                    var days = Math.round(Math.abs(millisBetween / (1000 * 3600 * 24)));

                    $.ajax({
                        "type": "POST",
                        "url": "@Url.Action("LeaveTracker")",
                        "datatype": 'json',
                        "data": { "startDate": startDate, "endDate": endDate, "days": days, "Description": description, "leaveId": leaveId },
                        "success": function (data) {
                            window.location.href = '@Url.Action("leavetracker","hrms")'
                            setinterval('location.reload()', 1000);
                        },
                        "error": function (data) {
                            alert("Error");

                        }
                    });
                        
                });

            });

        });

        function refreshPage() {
            location.reload(true);
        }

    </script>
}

HRMSWebpage/Views/HRMS/ProjectTracker.cshtml
@model IEnumerable<ProjectViewModel>

@{
    Layout = "_HRMSLayout";
}

<div class="container">
    <div class="card-header d-flex justify-content-between">
        Projects Assigned
    </div>
    <div class="card-body">
        <table class="table table-bordered">
            <tr>
                <th>@Html.DisplayNameFor(projects => projects.PrjtName)</th>
                <th>@Html.DisplayNameFor(projects => projects.PrjtDescription)</th>
                <th>@Html.DisplayNameFor(projects => projects.StartTime)</th>
                <th>@Html.DisplayNameFor(projects => projects.EndTime)</th>
                <th>@Html.DisplayNameFor(projects => projects.ProjectStatus)</th>
            </tr>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@Html.DisplayFor(projects => item.PrjtName)</td>
                    <td>@Html.DisplayFor(projects => item.PrjtDescription)</td>
                    <td>@Html.DisplayFor(projects => item.StartTime)</td>
                    <td>@Html.DisplayFor(projects => item.EndTime)</td>
                    <td>@Html.DisplayFor(projects => item.ProjectStatus)</td>
                </tr>
            }        
        </table>
    </div>
    <div class="card-footer"></div>
</div>

HRMSWebpage/Views/HRMS/SearchEmployee.cshtml
@model IEnumerable<EmpDeptPosSalViewModel>

@{
    Layout = "_HRMSLayout";
}

<div class="container">

    <section style="background-color: #eee;">
        <div class="container py-3">
            <div class="row">
                @foreach (var item in Model)
                {
                    <div class="col-md-12 col-lg-3 mb-1">
                        <div class="card">
                            <div class="d-flex justify-content-between p-3">
                                <p class="mb-0">@item.FirstName @item.LastName</p>
                                
                            </div>
                            <img src="~/images/@item.Image"
                             class="card-img-top" alt="Laptop" />
                            <div class="card-body">
                                <div class="d-flex justify-content-between">
                                    <p class="small"><a href="#!" class="text-muted">Phone Number</a></p>
                                    <p class="small text-danger">@item.PhoneNumber</p>
                                </div>
                                <div class="d-flex justify-content-between">
                                    <p class="small"><a href="#!" class="text-muted">Email</a></p>
                                    <p class="small text-danger">@item.Email</p>
                                </div>

                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>


</div>